""" TEXT to TSV Sample Map
The gatk GenomicsDBImport tool takes VCF files generated by the
HaplotypeCaller tool and compliles them. It is recomended that
no more than 50 VCFs be passed to GenomicsDBImport at a time.

A tab separated sample map can be used in place of specifying
every sample's name. This file should have on each line:

sample_name--tab--path_to_sample_vcf

This script takes in a preexisting sample names list and
outputs a sample name map
"""

def convert_to_tsv(txt):
    fragments= [] #will contain a list of frags lists
    #ex: [ ['KGF', '02',...], ['KGF', '03',...], .....]
    lines= txt.readlines()
    for line in lines:
        frags= line.split("_")
        fragments.append(frags)

    sample_names=[] # will contain name ex: KGF_02
    for frag_list in fragments:
        name= frag_list[0]+ "_" + frag_list[1]
        if name not in sample_names:
            sample_names.append(name)

    final_list=[]
    for ID in sample_names:
        sample_ID= "{}\t/lustre/project/kferris/Diana_Tataru/hybrids/4_GATKvarcall/1_GVCF_files{}/{}.g.vcf.gz".format(ID, WD, ID, end)
        final_list.append(sample_ID)

    return final_list #contains lists of file names followed by TAB, then path to file


    



if __name__ == "__main__":
    print("This script requires a sample names list (in format: KGF_02_...)\
and the path to the directoy containing the VCFs created by HaplotypeCaller")
    
    text_file= input("/Users/dianatataru/Desktop/sample_name_list.txt")
    WD= input("/lustre/project/kferris/Diana_Tataru/hybrids/4_GATKvarcall/1_GVCF_files")
    end=(".g.vcf.gz")
    #open the sample  names file
    file= open("/Users/dianatataru/Desktop/sample_name_list.txt", "r")
    sample_maps= convert_to_tsv(file)
    #write out to file
    map_file = open('sample_name_map.txt', 'w')
    for ID in sample_maps:
        map_file.writelines(ID+"\n")
    map_file.close()
     
