#!/bin/bash
#SBATCH --job-name=vcf2plink
#SBATCH --mail-type=ALL # Valid values: BEGIN, END, FAIL, REQUEUE and ALL.
#SBATCH --mail-user=dtataru@tulane.edu
#SBATCH --output=/lustre/project/kferris/Diana_Tataru/hybrids/4_GATKvarcall/error_vcf2plink/output1.out
#SBATCH --error=/lustre/project/kferris/Diana_Tataru/hybrids/4_GATKvarcall/error_jointgeno/error1.err
#SBATCH --qos=normal
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=20   #: Cpus per Task
#SBATCH --nodes=1            #: Number of Nodes
#SBATCH --ntasks-per-node=1  #: Number of Tasks per Node

echo "Start Job"

module load plink/1.9

cd /lustre/project/kferris/Diana_Tataru/hybrids/4_GATKvarcall/3_Genotyped_GVCFs/

plink --vcf hybrid1_jointgeno_v2.vcf --make-bed --keep-allele-order --out hybrid1_plink

module purge 

echo "end job"

